#!/usr/bin/env ruby

Dir[File.join(File.dirname(__FILE__), "lib", "*.rb")].each do |file|
  require file
end

def usage
  puts 'Usage: flexcp COMMAND [-p PROJECT] [command-specific-options]'
  puts ''
  puts 'Available commands, type "flexcp help COMMAND" for more details:'
  puts ''
  puts '  new       # create a project'
  puts '  list      # list all projects'
  puts '  delete    # delete a project'
  puts '  load      # load a file'
  puts '  process   # process the data'
  puts ''
end

def error(command)
  puts "*   `#{command}` it's not a valid flexcp command"
end

if ARGV.empty?
  usage
  exit
end

command = ARGV.shift

admin = FlexCP::Admin.new
loader = FlexCP::Loader.new
processor = FlexCP::Processor.new

case command
  when 'new'
    admin.new("eso")
  when 'list'
    admin.list
  when 'delete'
    admin.delete("eso")
  when 'load'
    if ARGV.empty?
      loader.help
      exit
    end
    
    filename = ARGV.shift
    loader.load filename
  when 'process'
  when 'help'
    help_command = ARGV.shift
    case help_command
      when 'new', 'delete', 'list'
        admin.help(help_command)
      when 'load'
        loader.help
      when 'process'
        processor.help
      else
        error(help_command)  
    end
  when '--help' , '-h'
    usage
  else
    error(ARGV.first)
end
