#!/usr/bin/env ruby
$LOAD_PATH << './lib'

require 'loader'
require 'processor'

def usage
  puts 'Usage: flexcp COMMAND [-p PROJECT] [command-specific-options]'
  puts ''
  puts 'Available commands, type "flexcp help COMMAND" for more details:'
  puts ''
  puts '  load      # load a file'
  puts '  process   # process the data'
  puts ''
end

def error(command)
  puts "*   `#{command}` it's not a valid flexcp command"
end

if ARGV.empty?
  usage
  exit
end

command = ARGV.shift

loader = FlexCP::Loader.new
processor = FlexCP::Processor.new

case command
  when 'load'
  when 'process'
  when 'help'
    help_command = ARGV.shift
    case help_command
      when 'load'
        loader.help
      when 'process'
        processor.help
      else
        error(help_command)  
    end
  when '--help' , '-h'
    usage
  else
    error(ARGV.first)
end
